# feeds_ex_xml_mapping configuration.
feeds.feed_type.*.third_party.feed_ex_xml_mapping:
  type: mapping
  label: 'Override mapping per feed'
  mapping:
    source:
      type: boolean
      label: 'Override source mapping'
    source_configuration:
      type: boolean
      label: 'Override source mapping configuration'
